Validate repeatable directives on schema
absinthe-graphql/absinthe pull request #1179
Opened 2022-07-13 14:27 UTC by maartenvanvliet

This PR adds validations to check whether a directive can be applied multiple times on a node. This was already done in the document pipeline, but not in the schema pipeline.

Also includes a small fix for the `deprecate` macro requiring a deprecation reason. In the graphql spec the reason is not required, so we can also allow `nil` here.

Fixes https://github.com/absinthe-graphql/absinthe/issues/1177

2022-07-13 14:37 UTC, benwilson512 requested changes
This looks great, can we add a `[Breaking Bugfix]` line to the `changelog` about this?

2022-07-13 14:40 UTC, maartenvanvliet commented
yes. done :)

2022-08-07 16:21 UTC, kdawgwilk approved these changes
Thanks for this! ❤️

2022-09-07 21:50 UTC, benwilson512 approved these changes

2022-09-07 21:50 UTC, merged