Fix non-null-list-of-non-null error when root data is nil
absinthe-graphql/absinthe pull request #1259
Opened 2023-08-03 15:18 UTC by tamanugi

Thanks for awesome library ✨

This PR is fix  https://github.com/absinthe-graphql/absinthe/issues/1256

2023-08-04 03:10 UTC, benwilson512 requested changes
Hey @tamanugi thanks for taking a crack at fixing this!

This fix may be useful on its own, but it is not testing the scenario that the issue outlines. At a core level, the issue is about fields with return type `non_null(list_of(:string))` but you are testing fields with return type `non_null(list_of(non_null(:string)))`.

You need a test that uses field return type `non_null(list_of(:string))` and exhibits the error message in the issue, that is then fixed by your changes.

Your change DOES fix a crash, which is great! This might be the same root cause as the crash described in the issue but since the return types don't match I'm not sure.

Please add in this test and we'll be good to go!

2023-08-05 15:49 UTC, tamanugi commented
Hi @benwilson512 ,  Thanks for review ✨ 

You are right, the test should have been for `non_null(list_of(:string))`.

I have fixed the test 👍 
556a8cc9a4d6a5199d10477cd1674e67d8c3cc03

2023-08-05 20:36 UTC, benwilson512 commented
Hey @tamanugi thanks for your continued effort. I'm going to push some changes up I think that better distinguish between `child` and `element`. In the existing tests `child` refers to a subfield, not an item in the list. I think this ambiguity is making it difficult to determine which test is supposed to cover which scenario.

I'm not entirely convinced that this does the right thing for lists of nullable that return `[nil]` but I should be able to see that more clearly shortly.

2023-08-05 20:37 UTC, benwilson512 commented on test/absinthe/phase/execution/non_null_test.exs
> +        nonNullListOfNonNull(makeChildNull: true) { __typename }
I don't see why this test is modified.

2023-08-05 20:37 UTC, benwilson512 commented on test/absinthe/phase/execution/non_null_test.exs
> +                nonNullListOfNonNull(makeChildNull: true) { __typename }
This test also should not be modified.

2023-08-05 20:37 UTC, benwilson512 commented on test/absinthe/phase/execution/non_null_test.exs
> +      assert {:ok, %{data: data, errors: errors}} == Absinthe.run(doc, Schema)
This test covers the case where an error is returned, but there is still no test case that shows that there is NOT an error for `[nil]` when it's allowed. I'll add one.

2023-08-05 20:46 UTC, benwilson512 commented on test/absinthe/phase/execution/non_null_test.exs
> +        nonNullListOfNonNull(makeChildNull: true) { __typename }
OH I see the semantics of `make_null` was changed.

2023-08-05 20:48 UTC, benwilson512 commented
OK I see what you were doing now. In the future as a bit of advice for open source contributions please add some comments to the PR to explain why you're changing existing tests. I get why you did it now because we need to distinguish between making the whole field `null` vs making an element in the list `null`. However when PRs change existing tests it always complicates things cause I am not sure why existing test behavior would need to change.

2023-08-05 20:49 UTC, benwilson512 commented
Right and the thing is if you're changing the argument name then you should change EVERY test that uses that argument because now they're testing different things.

2023-08-05 21:08 UTC, benwilson512 commented on test/absinthe/phase/execution/non_null_test.exs
> +    end
OK! This is the test that the issue is about, and this test fails on this PR. Now to figure out why.

2023-08-05 21:23 UTC, benwilson512 approved these changes
Thanks for digging into this, glad we could get it in a good spot!

2023-08-05 21:23 UTC, benwilson512 commented on lib/absinthe/phase/document/execution/resolution.ex
> +  defp maybe_add_non_null_error([], nil, %Type.NonNull{}) do
Moved this up as this the most fundamental check, best to do it first.

2023-08-05 21:23 UTC, benwilson512 commented on lib/absinthe/phase/document/execution/resolution.ex
> +  defp maybe_add_non_null_error([], values, %Type.List{of_type: %Type.NonNull{}})
Before, this clause would happen for any `non_null(list_of(` regardless of wether the inner type was `non_null` or not. Now we check the inner type properly.

2023-08-05 21:24 UTC, merged

2023-08-07 09:08 UTC, tamanugi commented
@benwilson512 
Thanks for your follow-up and awesome advice✨  
I have limited experience with OSS, so it was very educational for me.

2023-08-07 11:36 UTC, benwilson512 commented
Thanks for your contribution!